version: '3.8'
services:
  go-app:
    build: ./go-app
    ports:
      - "8080:8080"
  nextjs-app:
    build: ./nextjs-app
    ports:
      - "3000:3000"
  wordpress:
    build: ./wordpress-site
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
  db:
    image: arm64v8/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"