name: Go CI
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'
    - name: Install dependencies
      run: go mod tidy
    - name: Run linter
      run: golangci-lint run ./...
    - name: Run tests
      run: go test ./...
    - name: Build Docker image
      run: docker build -t deepakshiwani2000/go-app .
    - name: Push Docker image
      run: |
        docker tag deepakshiwani2000/go-app:latest deepakshiwani2000/go-app:${{ github.sha }}
        docker push deepakshiwani2000/go-app:latest
        docker push deepakshiwani2000/go-app:${{ github.sha }}
    - name: Deploy to staging
      run: echo "Deploying Go application to staging..."
    